platform :ios, '13.0'

use_frameworks!

target 'EiteiQRScanner' do
  
    pod 'EiteiQR', :git => 'https://github.com/JunEitei/EiteiQR', :tag => '3.3.0'

   # 開発に使ってるもんや
   # pod 'EiteiQR', :path => '../'
  
end
